### ISSUE TITLE
TypeError?

### ISSUE THREAD

**Issue by Snowi1** [adrienluitot/surfshark-linux-client#12]
Hello,

I have entered the command: python3 surfshark_client.py (knowing that python on its own doesn't work because it is outdated somehow) but now it shows a new error that I don't know how to fix, here's what it shows:

```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Traceback (most recent call last):
  File "surfshark_client.py", line 445, in <module>
    Main()
  File "surfshark_client.py", line 58, in __init__
    Gtk.StyleContext.add_provider_for_screen(
TypeError: Argument 0 does not allow None as a value
```

So, I don't know if there's an error with my connection or something??

Thank you in advance!

**Comment by adrienluitot** [comment]
Hello,
I'm not quite sure of what does that, but I think it might be an issue of dependence.
Do you have PyGObject ? Try installing it : `sudo pip install pygobject`
I realised I didn't put it in the `requirement.txt`, I will fix this in a future commit.

Though, it's strange indeed that you have this error about connection. Make sure you can access to this URL: `https://api.surfshark.com/v3/server/clusters/all` (from your browser for instance).
And anyway, I don't think it would cause the following error.

**Comment by Snowi1** [comment]
I think I might have a few problems of installation for some of those otherwise I can't figure it out either.
Would you know how to actually get the killswitch to work just from the Terminal, if it is possible of course!

**Comment by adrienluitot** [comment]
Well, it's a pity, it would be better to fix the problems.
For the killswitch I'm not sure, I didn't work on this part, but I think you would need a script.
